<?php

namespace Application;

use Application\Entity\Post;

?>

<h1>Posts</h1>

<div class="row">

    <div class="col-md-8">

        <?php /** @var Post $post */ ?>
        <?php foreach($posts as $post): ?>

            <h3>
                <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
                    <?= $this->escapeHtml($post->getTitle()); ?>
                </a>
            </h3>

            <p>
                Published: <?= $this->escapeHtml($post->getDateCreated()->format('jS \of F Y')); ?>
                | Tags: <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?>
            </p>

            <p class="comments-header">
                <?= $this->escapeHtml($postManager->getCommentCountStr($post)); ?> |
                <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()],
                    ['fragment'=>'comment']); ?>">
                    Add new comment
                </a>
            </p>

            <p>
                <?= $this->escapeHtml($post->getContent()); ?>
            </p>

        <?php endforeach; ?>

        <?= $this->paginationControl($posts,
            'Sliding',
            'application/partial/paginator',
            ['route' => 'application', 'tag' => $tag]); ?>

    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Popular Tags</h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->tagCloud as $tagName => $frequency): ?>

                    <a href="<?= $this->url('application', ['action'=>'index'],
                        ['query'=>['tag'=>$tagName]]); ?>">

                    <span style="font-size:<?= ceil(10 * $frequency); ?>em">
                        <?= $this->escapeHtml($tagName); ?>
                    </span>

                    </a>

                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>